Chore/rlz 2882 update docs sdk
railz-ai/railz-visualizations pull request #137
Opened 2023-05-05 16:49 UTC by cfenos

2023-05-08 16:19 UTC, mashuoyi111 commented on CONTRIBUTING.md
>  ### Issues
we might need a spacing between 193 and 194

2023-05-08 16:27 UTC, mashuoyi111 approved these changes
left a comment, otherwise looks good

2023-05-08 18:40 UTC, gchittolina commented on README.md
> +              { token: configuration.token.slice(0, 20) + '...', debug: configuration.debug },
maybe it's because the API returns `Bearer` at the beginning, not sure. Can you please double check? @cfenos

2023-06-19 16:23 UTC, Abiwax requested changes

2023-06-19 16:23 UTC, Abiwax commented on CONTRIBUTING.md
> +## Endpoints - Testing with local or QA data
this is for internal usage and shouldn't be exposed to the public

2023-06-19 16:23 UTC, Abiwax commented on packages/components/src/elements/core/readme.md
> +----------------------------------------------
stencil automatically generates these files, if this was updated by you, you should revert and let stencil generate it if not, when you merge, it will cause issues with the build. Best way to let this generate is by running stencil build

2023-06-19 16:23 UTC, Abiwax commented on CONTRIBUTING.md
this file is for contributing guidelines, Local development options should not be added here, you can add it to its own file and add a reference here and in the main Readme

2023-06-19 16:32 UTC, spersico commented on CONTRIBUTING.md
> +## Endpoints - Testing with local or QA data
I understand that, but… it **should** be explained **somewhere**, isn't it? 
IMO, as long as it's on the “Local development” file that you mentioned in another comment (so that it doesn't lead to customer devs thinking they need to use the endpoint prop to use the SDK), it's fine. What do you think?

2023-06-19 16:51 UTC, Abiwax commented on CONTRIBUTING.md
> +## Endpoints - Testing with local or QA data
@spersico, it can be added anywhere in an internal document but should not be added anywhere in this repo because it's an opensource repo that our customer's dev can also contribute to.

2023-06-19 17:22 UTC, cfenos commented on packages/components/src/elements/core/readme.md
> +----------------------------------------------
ok, just to be safe I reverted this file and then did stencil build. All should be good now! fixed your other comments as well @Abiwax

2023-06-19 17:25 UTC, cfenos commented on packages/components/src/elements/core/readme.md
> +----------------------------------------------
There is an issue with the development.md link here now, works locally. Looking into that now.

2023-06-19 17:46 UTC, cfenos commented on CONTRIBUTING.md
Done @Abiwax

2023-06-20 15:48 UTC, gchittolina approved these changes

2023-06-20 18:16 UTC, closed without merging