RLZ-3488 - financial ratios missing tooltip
railz-ai/railz-visualizations pull request #171
Opened 2024-10-03 19:49 UTC by ajain-railz

RLZ-3502 visualizations rebrand
- update tooltip for missing financial ratio
- update colours and logo

2024-10-04 00:53 UTC, railz-dev requested changes

2024-10-04 00:53 UTC, railz-dev commented on README.md
> +  <a href="https://www.fisglobal.com/" rel="noopener" target="_blank"><img width="200" src="./assets/images/fis-logo.svg" alt="FIS logo"></a>
Use the same logo as seen in https://github.com/railz-ai/railz-connect readme
the current logo used is favicon

2024-10-08 16:14 UTC, ajain-railz commented
Updated all the places I could find. Please check the License pages in particular if any changes are required.

2024-10-08 20:04 UTC, aadeniran-railz approved these changes

2024-10-09 15:54 UTC, merged