feat: Railz-score
railz-ai/railz-visualizations pull request #28
Opened 2022-03-28 21:04 UTC by allan-railz

2022-03-31 16:48 UTC, railz-dev requested changes
Added comments for updates required

2022-03-31 16:48 UTC, railz-dev commented on packages/components/src/elements/gauge-chart/test/gauge-chart.utils.spec.ts
> +    describe('success path', () => {
we should have a failure path as well

2022-03-31 16:48 UTC, railz-dev commented on packages/components/src/helpers/chart.utils.ts
> +export const ALL_FONTS = [
ALL_FONTS should be added to constants instead

2022-03-31 16:48 UTC, railz-dev commented on packages/components/src/helpers/utils.ts
> +    case RVReportTypes.SCORE:
should be RAILZ_SCORE because one all reporttypes are added, we won't need this switch anymore and will use the same conversion format we have on the dashboard

2022-03-31 16:48 UTC, railz-dev commented on packages/components/src/index.html
> +  <body>
i'll prefer if this example is in the examples folder than in the components index.html file

2022-04-01 14:51 UTC, allan-railz commented on packages/components/src/index.html
> +  <body>
We should have a ticket to add vanilla js. Right now this is in the whole StencilJS framework "development" mode. So this would be something diff. The example for VanillaJS is another thing.

2022-04-05 14:57 UTC, closed without merging