Feature/validate required fields
railz-ai/railz-visualizations pull request #65
Opened 2022-05-10 21:33 UTC by allan-railz

2022-05-11 21:09 UTC, allan-railz commented
Remove accountingMethod until this is publicly available.

2022-05-18 11:48 UTC, abisolaadeniran commented on packages/components/src/elements/bank-accounts/bank-accounts.utils.ts
> +      filter: pick(filter, [RVParams.SERVICE_NAME, RVParams.BUSINESS_NAME, RVParams.REPORT_TYPE]),
bank account does not need report type

2022-05-18 12:11 UTC, abisolaadeniran requested changes
Apart from the other comments below:
1. when wrong parameters are passed, we are supposed to show no data
its not showing anything. Passed businessName and serviceName
<img width="1628" alt="Screen Shot 2022-05-18 at 9 07 05 AM" src="https://user-images.githubusercontent.com/88153326/169035453-85036757-1629-4363-b172-d574be2ca6cb.png">

2. When wrong serviceName is passed, we make an API call, we should check if its a valid serviceName <img width="661" alt="Screen Shot 2022-05-18 at 9 09 29 AM" src="https://user-images.githubusercontent.com/88153326/169035512-ea718da9-d0dd-4994-8b87-4005038dc4ab.png">

2022-05-18 18:43 UTC, railz-dev commented
All handled.

2022-05-19 18:41 UTC, allanhal commented on packages/components/src/elements/bank-accounts/bank-accounts.utils.ts
> +      filter: pick(filter, [RVParams.SERVICE_NAME, RVParams.BUSINESS_NAME, RVParams.REPORT_TYPE]),
Do a URLMapping on the reports/requests

2022-05-20 14:11 UTC, allanhal commented on packages/components/src/elements/bank-accounts/bank-accounts.utils.ts
> +      filter: pick(filter, [RVParams.SERVICE_NAME, RVParams.BUSINESS_NAME, RVParams.REPORT_TYPE]),
Done

2022-05-20 14:58 UTC, abisolaadeniran commented
1. we are still not validating if serviceName is a valid service name and showing correct info, for Bills, Invoices and Railz Score, we are showing Oops, something went wrong instead of No data available
![Screen Shot 2022-05-20 at 11 52 00 AM](https://user-images.githubusercontent.com/88153326/169554917-e6fe956f-4902-44c2-939f-44d98ea9514e.png)

2. If no filter is passed, we are not logging any info letting them know we did not get the required data, also we are not showing the No data screen. Per requirement initially, the only time we won't load is if we don't get access token and we should definitely log if not passed
3. We are defaulting to plaid for bankAccounts even if they passed the wrong serviceName
4.  We are still sending reportType to bankAccounts API

2022-05-20 19:18 UTC, railz-dev commented
> Apart from the other comments below:
> 
> 1. when wrong parameters are passed, we are supposed to show no data
>    its not showing anything. Passed businessName and serviceName
> 
> <img alt="Screen Shot 2022-05-18 at 9 07 05 AM" width="1628" src="https://user-images.githubusercontent.com/88153326/169035453-85036757-1629-4363-b172-d574be2ca6cb.png">
> 
> 2. When wrong serviceName is passed, we make an API call, we should check if its a valid serviceName <img alt="Screen Shot 2022-05-18 at 9 09 29 AM" width="661" src="https://user-images.githubusercontent.com/88153326/169035512-ea718da9-d0dd-4994-8b87-4005038dc4ab.png">

Addressed.

2022-05-20 19:19 UTC, railz-dev commented
> 1. we are still not validating if serviceName is a valid service name and showing correct info, for Bills, Invoices and Railz Score, we are showing Oops, something went wrong instead of No data available
>    ![Screen Shot 2022-05-20 at 11 52 00 AM](https://user-images.githubusercontent.com/88153326/169554917-e6fe956f-4902-44c2-939f-44d98ea9514e.png)
> 2. If no filter is passed, we are not logging any info letting them know we did not get the required data, also we are not showing the No data screen. Per requirement initially, the only time we won't load is if we don't get access token and we should definitely log if not passed
> 3. We are defaulting to plaid for bankAccounts even if they passed the wrong serviceName
> 4. We are still sending reportType to bankAccounts API

Addressed.

2022-06-01 21:26 UTC, closed without merging