Feature/unsupported frameworks
railz-ai/railz-visualizations pull request #67
Opened 2022-05-16 23:16 UTC by allan-railz

2022-05-18 09:12 UTC, abisolaadeniran commented on README.md
> +```html
not needed here

2022-05-18 11:41 UTC, abisolaadeniran requested changes

2022-05-18 11:41 UTC, abisolaadeniran commented on examples/javascript/index.html
> +          businessName: document.getElementById('business-name').value,
a different way to get formdata is by wrapping the inputs into a form and getting the information like below
```
  const formElem = document.querySelector("form");
  const formData = new FormData(formElem);
  const businessName = formData.get("businessName");
```

2022-05-18 11:41 UTC, abisolaadeniran commented on examples/javascript/index.html
> +  businessName: '${document.getElementById('business-name').value}',
duplicate `getElementById`, values can be in a constant and filter data used in 292 and 306

2022-05-18 11:41 UTC, abisolaadeniran commented on examples/javascript/index.html
> +        const sourceCode = `
source code should show the way the data will be passed to railz visualizations

2022-05-18 19:34 UTC, railz-dev commented on examples/javascript/index.html
> +        const sourceCode = `
I think this is the easiest way to call.
If we go for:
<railz-visualizations configuration="[STRINGFY OBJECT]" ...

It would be kinda hard to read. Should I put this example up too?

2022-05-19 15:09 UTC, abisolaadeniran commented on examples/javascript/index.html
> +          endpoint: 'https://api.qa2.railz.ai',
lets remove endpoint value

2022-05-19 18:15 UTC, allanhal commented on examples/javascript/index.html
> +          endpoint: 'https://api.qa2.railz.ai',
Resolved

2022-06-14 17:50 UTC, abisolaadeniran requested changes

2022-06-15 12:36 UTC, abisolaadeniran approved these changes

2022-06-15 12:37 UTC, merged