chore: update en prefix (RLZ-1817)
railz-ai/railz-visualizations pull request #73
Opened 2022-05-30 14:41 UTC by cfenos

2022-05-30 14:53 UTC, railz-dev requested changes

2022-05-30 14:53 UTC, railz-dev commented on packages/components/src/config/translations/en.json
>    "NOT_ABLE_TO_RETRIEVE_REPORT_DATA": "Not able to retrieve report data.",
`RV`

2022-06-07 19:35 UTC, cfenos commented on packages/components/src/config/translations/en.json
>    "NOT_ABLE_TO_RETRIEVE_REPORT_DATA": "Not able to retrieve report data.",
@railz-dev done

2022-06-08 03:17 UTC, railz-dev approved these changes

2022-06-08 03:17 UTC, merged